# Generated by Django 4.2.3 on 2023-07-28 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professor', '0004_delete_plano'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_disc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor.periododisc')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User periodo',
                'verbose_name_plural': 'Users e periodos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Titulo')),
                ('resumo', models.TextField(null=True, verbose_name='Resumo')),
                ('objetivo', models.TextField(null=True, verbose_name='Objetivo')),
                ('obj_especifico', models.TextField(null=True, verbose_name='Objetivo especifico')),
                ('motivacao', models.TextField(null=True, verbose_name='Motivação')),
                ('status', models.CharField(max_length=150, verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.userperiodo')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ['id'],
            },
        ),
    ]
