# Generated by Django 4.2.3 on 2023-07-28 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0004_delete_plano'),
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='user_periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor.periododisc'),
        ),
        migrations.DeleteModel(
            name='UserPeriodo',
        ),
    ]
