# Generated by Django 4.2.3 on 2023-07-28 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0004_delete_plano'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aluno', '0002_alter_plano_user_periodo_delete_userperiodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='user_orientador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plano',
            name='user_periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Orientador', to='professor.periododisc'),
        ),
    ]
