# Generated by Django 4.2.3 on 2023-08-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0006_alter_plano_user_alter_plano_user_orientador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60, verbose_name='Titulo')),
                ('autor', models.CharField(max_length=60, verbose_name='Autor')),
                ('orientador', models.CharField(max_length=60, verbose_name='Orientador')),
                ('data', models.DateField()),
                ('banca', models.CharField(max_length=150, verbose_name='Banca')),
                ('resumo', models.TextField(null=True, verbose_name='Resumo')),
                ('palavras_ch', models.CharField(max_length=60, verbose_name='Palavras chaves')),
                ('arquivo', models.FileField(upload_to='media/Trabalhos/', verbose_name='Arquivo')),
            ],
            options={
                'verbose_name': 'Trabalho',
                'verbose_name_plural': 'Trabalhos',
                'ordering': ['id'],
            },
        ),
    ]
