# Generated by Django 4.2.3 on 2023-08-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0010_trabalho_prof3_alter_trabalho_prof2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabalho',
            name='titulo',
            field=models.CharField(max_length=60),
        ),
    ]
