# Generated by Django 4.2.3 on 2023-08-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0011_alter_trabalho_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabalho',
            name='prof3',
            field=models.CharField(default=1, max_length=60, verbose_name='Professor3'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='resumo',
            field=models.TextField(default=1, verbose_name='Resumo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='titulo',
            field=models.CharField(max_length=60, verbose_name='Titulo'),
        ),
    ]
