# Generated by Django 4.2.3 on 2023-08-08 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0012_alter_trabalho_prof3_alter_trabalho_resumo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabalho',
            name='arquivo',
        ),
    ]
