# Generated by Django 4.2.3 on 2023-08-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0013_remove_trabalho_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalho',
            name='arquivo',
            field=models.FileField(default=1, upload_to='Trabalhos/', verbose_name='Arquivo'),
            preserve_default=False,
        ),
    ]
