# Generated by Django 4.2.3 on 2023-08-23 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0015_alter_trabalho_orientador'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='arquivo',
            field=models.FileField(default=1, upload_to='plano_pdf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabalho',
            name='status',
            field=models.CharField(default=1, max_length=150, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
