# Generated by Django 4.2.3 on 2023-08-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0017_alter_trabalho_prof3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plano',
            name='titulo',
        ),
        migrations.AddField(
            model_name='plano',
            name='tema',
            field=models.CharField(default=1, max_length=150, verbose_name='Tema'),
            preserve_default=False,
        ),
    ]
