# Generated by Django 4.2.3 on 2023-11-16 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aluno', '0018_remove_plano_titulo_plano_tema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_aluno', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plano',
            name='user_orientador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_orientados', to=settings.AUTH_USER_MODEL),
        ),
    ]
