# Generated by Django 4.2.3 on 2023-11-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0019_alter_plano_user_alter_plano_user_orientador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='status',
            field=models.CharField(max_length=20, verbose_name='Status'),
        ),
    ]
