# Generated by Django 4.2.3 on 2023-07-25 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Nome',
                'verbose_name_plural': 'Nome',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Período',
                'verbose_name_plural': 'Período',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoDisc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor.disciplina')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='professor.periodo')),
            ],
            options={
                'verbose_name': 'Periodo_Disciplina',
                'verbose_name_plural': 'Periodos_Disciplinas',
                'ordering': ['id'],
            },
        ),
    ]
