# Generated by Django 4.2.3 on 2023-07-28 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0003_trabalho'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plano',
        ),
    ]
