# Generated by Django 4.2.3 on 2023-08-08 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0004_delete_plano'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trabalho',
        ),
    ]
